// Generated by gencpp from file slamdunk_msgs/ReconfigureLevels.msg
// DO NOT EDIT!


#ifndef SLAMDUNK_MSGS_MESSAGE_RECONFIGURELEVELS_H
#define SLAMDUNK_MSGS_MESSAGE_RECONFIGURELEVELS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slamdunk_msgs
{
template <class ContainerAllocator>
struct ReconfigureLevels_
{
  typedef ReconfigureLevels_<ContainerAllocator> Type;

  ReconfigureLevels_()
    {
    }
  ReconfigureLevels_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }




    enum { NODE = 1 };
     enum { STREAMING = 2 };
     enum { VIDEO_MODE = 4 };
     enum { VIDEO_SOURCE = 8 };
     enum { SERVICE_TRIGGER = 16 };
 

  typedef boost::shared_ptr< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> const> ConstPtr;

}; // struct ReconfigureLevels_

typedef ::slamdunk_msgs::ReconfigureLevels_<std::allocator<void> > ReconfigureLevels;

typedef boost::shared_ptr< ::slamdunk_msgs::ReconfigureLevels > ReconfigureLevelsPtr;
typedef boost::shared_ptr< ::slamdunk_msgs::ReconfigureLevels const> ReconfigureLevelsConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slamdunk_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'slamdunk_msgs': ['/home/me132/DroneVisionProject/DroneInterface/src/slamdunk_ros/slamdunk_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abb7323d211b806e7835ae01d4f75714";
  }

  static const char* value(const ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabb7323d211b806eULL;
  static const uint64_t static_value2 = 0x7835ae01d4f75714ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamdunk_msgs/ReconfigureLevels";
  }

  static const char* value(const ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Only local to the node code, no need to forward anything to kalamos context\n\
byte NODE = 1\n\
\n\
# Streaming options, should reconfigure kalamos context\n\
byte STREAMING = 2\n\
\n\
# General options, should reconfigure kalamos context\n\
byte VIDEO_MODE = 4\n\
\n\
# General options, should reconfigure kalamos context\n\
byte VIDEO_SOURCE = 8\n\
\n\
byte SERVICE_TRIGGER = 16\n\
";
  }

  static const char* value(const ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReconfigureLevels_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::slamdunk_msgs::ReconfigureLevels_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SLAMDUNK_MSGS_MESSAGE_RECONFIGURELEVELS_H
