// Generated by gencpp from file slamdunk_msgs/Save.msg
// DO NOT EDIT!


#ifndef SLAMDUNK_MSGS_MESSAGE_SAVE_H
#define SLAMDUNK_MSGS_MESSAGE_SAVE_H

#include <ros/service_traits.h>


#include <slamdunk_msgs/SaveRequest.h>
#include <slamdunk_msgs/SaveResponse.h>


namespace slamdunk_msgs
{

struct Save
{

typedef SaveRequest Request;
typedef SaveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Save
} // namespace slamdunk_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slamdunk_msgs::Save > {
  static const char* value()
  {
    return "8f0ff3fdc0ca2824ef8a013dd85740cd";
  }

  static const char* value(const ::slamdunk_msgs::Save&) { return value(); }
};

template<>
struct DataType< ::slamdunk_msgs::Save > {
  static const char* value()
  {
    return "slamdunk_msgs/Save";
  }

  static const char* value(const ::slamdunk_msgs::Save&) { return value(); }
};


// service_traits::MD5Sum< ::slamdunk_msgs::SaveRequest> should match 
// service_traits::MD5Sum< ::slamdunk_msgs::Save > 
template<>
struct MD5Sum< ::slamdunk_msgs::SaveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slamdunk_msgs::Save >::value();
  }
  static const char* value(const ::slamdunk_msgs::SaveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slamdunk_msgs::SaveRequest> should match 
// service_traits::DataType< ::slamdunk_msgs::Save > 
template<>
struct DataType< ::slamdunk_msgs::SaveRequest>
{
  static const char* value()
  {
    return DataType< ::slamdunk_msgs::Save >::value();
  }
  static const char* value(const ::slamdunk_msgs::SaveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slamdunk_msgs::SaveResponse> should match 
// service_traits::MD5Sum< ::slamdunk_msgs::Save > 
template<>
struct MD5Sum< ::slamdunk_msgs::SaveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slamdunk_msgs::Save >::value();
  }
  static const char* value(const ::slamdunk_msgs::SaveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slamdunk_msgs::SaveResponse> should match 
// service_traits::DataType< ::slamdunk_msgs::Save > 
template<>
struct DataType< ::slamdunk_msgs::SaveResponse>
{
  static const char* value()
  {
    return DataType< ::slamdunk_msgs::Save >::value();
  }
  static const char* value(const ::slamdunk_msgs::SaveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAMDUNK_MSGS_MESSAGE_SAVE_H
