// Generated by gencpp from file slamdunk_msgs/SaveRequest.msg
// DO NOT EDIT!


#ifndef SLAMDUNK_MSGS_MESSAGE_SAVEREQUEST_H
#define SLAMDUNK_MSGS_MESSAGE_SAVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slamdunk_msgs
{
template <class ContainerAllocator>
struct SaveRequest_
{
  typedef SaveRequest_<ContainerAllocator> Type;

  SaveRequest_()
    : path()
    , allowOverride(false)  {
    }
  SaveRequest_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , allowOverride(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;

   typedef uint8_t _allowOverride_type;
  _allowOverride_type allowOverride;




  typedef boost::shared_ptr< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveRequest_

typedef ::slamdunk_msgs::SaveRequest_<std::allocator<void> > SaveRequest;

typedef boost::shared_ptr< ::slamdunk_msgs::SaveRequest > SaveRequestPtr;
typedef boost::shared_ptr< ::slamdunk_msgs::SaveRequest const> SaveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamdunk_msgs::SaveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slamdunk_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'slamdunk_msgs': ['/home/me132/DroneVisionProject/DroneInterface/src/slamdunk_ros/slamdunk_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f0ff3fdc0ca2824ef8a013dd85740cd";
  }

  static const char* value(const ::slamdunk_msgs::SaveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f0ff3fdc0ca2824ULL;
  static const uint64_t static_value2 = 0xef8a013dd85740cdULL;
};

template<class ContainerAllocator>
struct DataType< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamdunk_msgs/SaveRequest";
  }

  static const char* value(const ::slamdunk_msgs::SaveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
string path\n\
\n\
bool allowOverride\n\
";
  }

  static const char* value(const ::slamdunk_msgs::SaveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.allowOverride);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamdunk_msgs::SaveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamdunk_msgs::SaveRequest_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
    s << indent << "allowOverride: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.allowOverride);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMDUNK_MSGS_MESSAGE_SAVEREQUEST_H
