// Generated by gencpp from file slamdunk_msgs/ServiceTrigger.msg
// DO NOT EDIT!


#ifndef SLAMDUNK_MSGS_MESSAGE_SERVICETRIGGER_H
#define SLAMDUNK_MSGS_MESSAGE_SERVICETRIGGER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slamdunk_msgs
{
template <class ContainerAllocator>
struct ServiceTrigger_
{
  typedef ServiceTrigger_<ContainerAllocator> Type;

  ServiceTrigger_()
    {
    }
  ServiceTrigger_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }




    enum { TRIGGER_MIN = 0 };
     enum { ON_DEMAND = 0 };
     enum { ALWAYS = 1 };
     enum { NEVER = 2 };
     enum { TRIGGER_MAX = 2 };
 

  typedef boost::shared_ptr< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceTrigger_

typedef ::slamdunk_msgs::ServiceTrigger_<std::allocator<void> > ServiceTrigger;

typedef boost::shared_ptr< ::slamdunk_msgs::ServiceTrigger > ServiceTriggerPtr;
typedef boost::shared_ptr< ::slamdunk_msgs::ServiceTrigger const> ServiceTriggerConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slamdunk_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'slamdunk_msgs': ['/home/me132/DroneVisionProject/DroneInterface/src/slamdunk_ros/slamdunk_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bac24ec0808c0471662183b689f61b6b";
  }

  static const char* value(const ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbac24ec0808c0471ULL;
  static const uint64_t static_value2 = 0x662183b689f61b6bULL;
};

template<class ContainerAllocator>
struct DataType< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamdunk_msgs/ServiceTrigger";
  }

  static const char* value(const ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "byte TRIGGER_MIN = 0\n\
\n\
# Automatically start the service when there are subscribers to its topic(s),\n\
# or when another service requires it.\n\
byte ON_DEMAND = 0\n\
\n\
# Always run the service.\n\
#\n\
# Note: the service may still not run if it depends on a disabled service.\n\
byte ALWAYS = 1\n\
\n\
# Never run the service,\n\
# even if some other service depends on it.\n\
byte NEVER = 2\n\
\n\
byte TRIGGER_MAX = 2\n\
";
  }

  static const char* value(const ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceTrigger_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::slamdunk_msgs::ServiceTrigger_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SLAMDUNK_MSGS_MESSAGE_SERVICETRIGGER_H
