// Generated by gencpp from file slamdunk_msgs/StreamingTypes.msg
// DO NOT EDIT!


#ifndef SLAMDUNK_MSGS_MESSAGE_STREAMINGTYPES_H
#define SLAMDUNK_MSGS_MESSAGE_STREAMINGTYPES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slamdunk_msgs
{
template <class ContainerAllocator>
struct StreamingTypes_
{
  typedef StreamingTypes_<ContainerAllocator> Type;

  StreamingTypes_()
    {
    }
  StreamingTypes_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }




    enum { TYPE_MIN = 0 };
     enum { TYPE_RTP = 0 };
     enum { TYPE_FILE = 1 };
     enum { TYPE_MAX = 1 };
 

  typedef boost::shared_ptr< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> const> ConstPtr;

}; // struct StreamingTypes_

typedef ::slamdunk_msgs::StreamingTypes_<std::allocator<void> > StreamingTypes;

typedef boost::shared_ptr< ::slamdunk_msgs::StreamingTypes > StreamingTypesPtr;
typedef boost::shared_ptr< ::slamdunk_msgs::StreamingTypes const> StreamingTypesConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slamdunk_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'slamdunk_msgs': ['/home/me132/DroneVisionProject/DroneInterface/src/slamdunk_ros/slamdunk_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8538d0b43c315fff9cbb5e3d634bc8c";
  }

  static const char* value(const ::slamdunk_msgs::StreamingTypes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8538d0b43c315ffULL;
  static const uint64_t static_value2 = 0xf9cbb5e3d634bc8cULL;
};

template<class ContainerAllocator>
struct DataType< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamdunk_msgs/StreamingTypes";
  }

  static const char* value(const ::slamdunk_msgs::StreamingTypes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# available streaming types\n\
\n\
byte TYPE_MIN = 0\n\
\n\
byte TYPE_RTP = 0\n\
byte TYPE_FILE = 1\n\
\n\
byte TYPE_MAX = 1\n\
";
  }

  static const char* value(const ::slamdunk_msgs::StreamingTypes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StreamingTypes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamdunk_msgs::StreamingTypes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::slamdunk_msgs::StreamingTypes_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SLAMDUNK_MSGS_MESSAGE_STREAMINGTYPES_H
